//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"go/format"
	"log"
	"os"
	"text/template"

	"gopkg.in/yaml.v3"
)

type YamlROS map[string]map[string][]struct {
	TF string
	MT string
}

func main() {
	m := YamlROS{}
	fileIn, err := os.Open("mikrotik_resource_drift.yaml")
	if err != nil {
		log.Fatalf("error: %v", err)
	}
	defer fileIn.Close()

	dec := yaml.NewDecoder(fileIn)
	if err := dec.Decode(&m); err != nil {
		log.Fatal(err)
	}
	var generated bytes.Buffer
	if err := driftTemplate.Execute(&generated, m); err != nil {
		log.Fatal(err)
	}
	source, err := format.Source(generated.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("mikrotik_resource_drift.go", source, 0644); err != nil {
		log.Fatal(err)
	}
}

var driftTemplate = template.Must(template.New("").Parse(`// Code generated by "tools/drift/main.go"; DO NOT EDIT.
package routeros

func init() {
{{- range $version, $resource := . }}
  {{- range $name, $attributes := $resource }}
    {{- range $attr := $attributes }}
    {{ printf "driftAttributeSlice.Add(%q, %q, %q, %q)" $version $name $attr.TF $attr.MT }}
    {{- end }}
  {{- end }}
{{- end }}
    driftAttributeSlice.SortDesc()
}
`))
